spring:
  application:
    name: spring-boot-intro

  datasource:
    jdbc-url: jdbc:h2:mem:test1
    driver-class-name: org.h2.Driver
    username: root
    password: root

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

      resourceserver:
        jwt:
          issuer-uri: https://github.com


server:
  port: 8090